# Generated by Django 4.2 on 2025-03-16 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100, verbose_name='活动类型')),
                ('preferred_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='偏好时间')),
                ('interests', models.JSONField(default=list, verbose_name='兴趣爱好')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置')),
                ('status', models.CharField(choices=[('pending', '待匹配'), ('matched', '已匹配'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to=settings.AUTH_USER_MODEL, verbose_name='匹配用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搭子请求',
                'verbose_name_plural': '搭子请求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('day_of_week', models.IntegerField(verbose_name='星期几(1-7)')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='上课地点')),
                ('semester', models.CharField(max_length=100, verbose_name='学期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课表',
                'verbose_name_plural': '课表',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('content', models.JSONField(verbose_name='日程内容')),
                ('preferences', models.JSONField(blank=True, null=True, verbose_name='时间偏好')),
                ('avoid_times', models.JSONField(blank=True, null=True, verbose_name='避开时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '日程规划',
                'verbose_name_plural': '日程规划',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
