# Generated by Django 4.2 on 2025-03-16 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='待办描述')),
                ('execution_preference', models.CharField(blank=True, max_length=100, null=True, verbose_name='执行时间偏好')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '宿舍待办事项',
                'verbose_name_plural': '宿舍待办事项',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='位置')),
                ('weather_info', models.CharField(max_length=200, verbose_name='天气信息')),
                ('temperature', models.CharField(max_length=50, verbose_name='温度')),
                ('health_tips', models.TextField(verbose_name='养生建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '天气记录',
                'verbose_name_plural': '天气记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpressPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='快递单号')),
                ('carrier', models.CharField(blank=True, max_length=100, null=True, verbose_name='快递公司')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '运输中'), ('arrived', '已到达'), ('delivered', '已签收')], default='pending', max_length=20, verbose_name='快递状态')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='当前位置')),
                ('pickup_suggestion', models.CharField(blank=True, max_length=200, null=True, verbose_name='取件建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_packages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '快递包裹',
                'verbose_name_plural': '快递包裹',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryTaskCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='是否接受')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_tasks', to=settings.AUTH_USER_MODEL, verbose_name='协作者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='life_assistant.dormitorytask', verbose_name='待办事项')),
            ],
            options={
                'verbose_name': '宿舍待办协作',
                'verbose_name_plural': '宿舍待办协作',
                'unique_together': {('task', 'collaborator')},
            },
        ),
    ]
