# Generated by Django 4.2 on 2025-03-16 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资源标题')),
                ('duration', models.CharField(max_length=50, verbose_name='资源时长')),
                ('url', models.URLField(verbose_name='资源链接')),
                ('category', models.CharField(max_length=100, verbose_name='资源分类')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习资源',
                'verbose_name_plural': '学习资源',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=500, verbose_name='指令内容')),
                ('execution_result', models.TextField(verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '语音指令',
                'verbose_name_plural': '语音指令',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('focus_time', models.IntegerField(verbose_name='专注时长(分钟)')),
                ('rest_time', models.IntegerField(verbose_name='休息时长(分钟)')),
                ('savings_amount', models.FloatField(blank=True, null=True, verbose_name='存钱金额')),
                ('completed_focus_time', models.IntegerField(default=0, verbose_name='已完成专注时长(分钟)')),
                ('unlocked_savings', models.FloatField(default=0.0, verbose_name='已解锁存钱金额')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习计划',
                'verbose_name_plural': '学习计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FragmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_task', models.CharField(max_length=200, verbose_name='父任务')),
                ('fragment_time', models.IntegerField(verbose_name='碎片时间(分钟)')),
                ('micro_tasks', models.JSONField(verbose_name='微任务列表')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragment_tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '碎片化任务',
                'verbose_name_plural': '碎片化任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=100, verbose_name='情绪')),
                ('sensor_data', models.JSONField(blank=True, null=True, verbose_name='传感器数据')),
                ('adjustment_suggestion', models.TextField(verbose_name='调节建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '情绪记录',
                'verbose_name_plural': '情绪记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=200, verbose_name='任务描述')),
                ('execution_time', models.CharField(max_length=100, verbose_name='执行时间')),
                ('repeat_pattern', models.CharField(blank=True, max_length=100, null=True, verbose_name='重复模式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '自动执行任务',
                'verbose_name_plural': '自动执行任务',
                'ordering': ['execution_time'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_description', models.CharField(max_length=500, verbose_name='目标描述')),
                ('time_range', models.CharField(max_length=100, verbose_name='时间范围')),
                ('current_level', models.CharField(blank=True, max_length=200, null=True, verbose_name='当前水平')),
                ('plan_content', models.JSONField(verbose_name='计划内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI生成学习计划',
                'verbose_name_plural': 'AI生成学习计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResourceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='personal_growth.learningresource', verbose_name='资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资源收藏',
                'verbose_name_plural': '用户资源收藏',
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
