# Generated by Django 4.2 on 2025-03-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_growth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
