# Generated by Django 4.2 on 2025-03-17 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_growth', '0002_remove_plan_is_completed_plan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['scheduled_date', '-created_at'], 'verbose_name': '学习计划', 'verbose_name_plural': '学习计划'},
        ),
        migrations.AddField(
            model_name='plan',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='计划执行日期'),
        ),
    ]
