# Generated by Django 4.2 on 2025-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_growth', '0003_alter_plan_options_plan_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='completed_focus_time',
            field=models.PositiveIntegerField(default=0, verbose_name='已完成专注时长(分钟)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='focus_time',
            field=models.PositiveIntegerField(verbose_name='专注时长(分钟)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='rest_time',
            field=models.PositiveIntegerField(verbose_name='休息时长(分钟)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='savings_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='存钱金额'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unlocked_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已解锁金额'),
        ),
    ]
