# Generated by Django 4.2.2 on 2025-04-26 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_growth', '0004_plan_start_time_alter_plan_completed_focus_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='会话标题')),
                ('status', models.CharField(choices=[('created', '已创建'), ('in_progress', '进行中'), ('paused', '已暂停'), ('completed', '已完成')], default='created', max_length=20, verbose_name='状态')),
                ('focus_minutes', models.IntegerField(default=25, verbose_name='专注时长(分钟)')),
                ('break_minutes', models.IntegerField(default=5, verbose_name='休息时长(分钟)')),
                ('long_break_minutes', models.IntegerField(default=15, verbose_name='长休息时长(分钟)')),
                ('long_break_interval', models.IntegerField(default=4, verbose_name='长休息间隔')),
                ('completed_pomodoros', models.IntegerField(default=0, verbose_name='已完成番茄钟数量')),
                ('planned_pomodoros', models.IntegerField(default=0, verbose_name='计划番茄钟数量')),
                ('total_focus_time', models.IntegerField(default=0, verbose_name='总专注时长(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='personal_growth.plan', verbose_name='关联任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '番茄钟会话',
                'verbose_name_plural': '番茄钟会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_number', models.IntegerField(verbose_name='番茄钟序号')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('actual_duration', models.IntegerField(default=0, verbose_name='实际持续时间(分钟)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='笔记')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_records', to='personal_growth.pomodorosession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '番茄钟记录',
                'verbose_name_plural': '番茄钟记录',
                'ordering': ['session', 'pomodoro_number'],
                'unique_together': {('session', 'pomodoro_number')},
            },
        ),
    ]
