# Generated by Django 4.2.2 on 2025-04-26 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_growth', '0005_pomodorosession_pomodororecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotask',
            name='reminder_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='提前提醒时间(分钟)'),
        ),
        migrations.AddField(
            model_name='autotask',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='计划执行日期'),
        ),
    ]
