# Generated by Django 4.2 on 2025-03-16 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='自习室名称')),
                ('room_type', models.CharField(choices=[('fragment', '碎片化自习室'), ('standard', '标准自习室'), ('ai_hosted', 'AI主持自习室')], max_length=20, verbose_name='自习室类型')),
                ('topic', models.CharField(max_length=100, verbose_name='学习主题')),
                ('max_users', models.IntegerField(default=10, verbose_name='最大用户数')),
                ('current_users', models.IntegerField(default=0, verbose_name='当前用户数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自习室',
                'verbose_name_plural': '自习室',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('leave_time', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('study_goal', models.CharField(blank=True, max_length=200, null=True, verbose_name='学习目标')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='virtual_study_room.studyroom', verbose_name='自习室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_room_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '自习室成员',
                'verbose_name_plural': '自习室成员',
                'ordering': ['-join_time'],
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='学习时长(分钟)')),
                ('content', models.TextField(verbose_name='学习内容')),
                ('completion_rate', models.FloatField(verbose_name='完成率')),
                ('blockchain_hash', models.CharField(blank=True, max_length=200, null=True, verbose_name='区块链哈希')),
                ('verification_url', models.URLField(blank=True, null=True, verbose_name='验证链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='virtual_study_room.studyroom', verbose_name='自习室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIHostedStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_goal', models.CharField(max_length=200, verbose_name='自习室目标')),
                ('duration', models.IntegerField(verbose_name='计划时长(分钟)')),
                ('suggestions', models.TextField(blank=True, null=True, verbose_name='AI建议')),
                ('summary_report', models.TextField(blank=True, null=True, verbose_name='总结报告')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='virtual_study_room.studyroom', verbose_name='自习室')),
            ],
            options={
                'verbose_name': 'AI主持自习会话',
                'verbose_name_plural': 'AI主持自习会话',
                'ordering': ['-start_time'],
            },
        ),
    ]
